import {
  PlusCircleOutlined,
  PlusOutlined,
  CheckOutlined,
  EditOutlined,
  ArrowRightOutlined,
  NodeIndexOutlined,
  ThunderboltOutlined,
  DeleteOutlined,
  SearchOutlined,
  SyncOutlined,
  DragOutlined,
  AppstoreOutlined,
  ControlOutlined,
  UploadOutlined,
  ArrowLeftOutlined,
  LeftOutlined,
  RightOutlined,
  CloseOutlined,
  SwapOutlined,
  CompressOutlined,
  ExpandOutlined,
  EllipsisOutlined,
  ZoomInOutlined,
  ZoomOutOutlined,
  UndoOutlined,
  RedoOutlined,
  LikeOutlined,
  DownOutlined,
  QuestionCircleOutlined,
  CaretUpOutlined,
  CaretDownOutlined,
  EyeOutlined,
  InfoCircleOutlined
} from "@ant-design/icons-vue";

const icons: any = {
  SearchOutlined,
  PlusCircleOutlined,
  PlusOutlined,
  CheckOutlined,
  EditOutlined,
  ArrowRightOutlined,
  NodeIndexOutlined,
  ThunderboltOutlined,
  DeleteOutlined,
  SyncOutlined,
  DragOutlined,
  AppstoreOutlined,
  ControlOutlined,
  UploadOutlined,
  ArrowLeftOutlined,
  LeftOutlined,
  RightOutlined,
  CloseOutlined,
  SwapOutlined,
  CompressOutlined,
  ExpandOutlined,
  EllipsisOutlined,
  ZoomInOutlined,
  ZoomOutOutlined,
  UndoOutlined,
  RedoOutlined,
  LikeOutlined,
  DownOutlined,
  QuestionCircleOutlined,
  CaretUpOutlined,
  CaretDownOutlined,
  EyeOutlined,
  InfoCircleOutlined
};
export default function (app: any) {
  for (const key in icons) {
    app.component(key, icons[key]);
  }
}
