import { createApp } from "vue";
import "./style.css";
import App from "./App.vue";
import Antd from "ant-design-vue";
import "ant-design-vue/dist/antd.less";
import UiAntdv from "@fast-crud/ui-antdv";
const app = createApp(App);
app.use(Antd);
app.use(UiAntdv);
app.mount("#app");
